name: TundereAdmin
author: tsuttsu305
description: TundereServer Administration Plugin
website: http://info.tundere.mydns.jp/
main: jp.mydns.tundere.TundereAdmin
version: 0.0.1
commands:
  tundereadmin:
    description: helpCmd
    permission: tundere.help
    usage: /tundereadmin
  msg:
    description: MsgCmd
    permission: tundere.msg
    usage: /msg
  warp:
    description: WarpCmd
    permission: tundere.warp
    usage: /warp
  afk:
    description: AFKCmd
    permission: tundere.afk
    usage: /afk
  spawner:
    aliases: [spb]
    description: SpawnerCmd
    permission: tundere.spanwer
    usage: /spawner